### ISSUE TITLE
Error: %1 is not a valid Win32 application after upgrade

### ISSUE THREAD

**Issue by benjcresswell** [electron-userland/electron-spellchecker#100]
We have an application using this module which builds and works perfectly when using an installer. However, after the app gets upgraded using Squirrel we get the following error:

Error: %1 is not a valid Win32 application

I've seen in two other issues raised that the advice we to following the guidance on native modules. However, as part of our build process we are using electron-rebuild before generating each new version of the app. That version is then sent to the Squirrel server and downloaded by the clients. After which we get the error.

Any advice?

**Comment by Slapbox** [comment]
Very unlikely to help, but I once had a similar issue with a native dependency (not using Squirrel) and ensuring the entire `node_modules` directory was not set to `read-only` resolved it. Like I said very unlikely to help though.

**Comment by benjcresswell** [comment]
We found the issue in the end which was that regardless of the architecture which was sent to the Nuts server, the 32x version was being returned which was causing problems with the compiling of modules.
