### ISSUE TITLE
Question: How to Change BrowserWindow (Chromium) context menu language

### ISSUE THREAD

**Issue by WilliamHolmes** [electron-userland/electron-spellchecker#114]
ref: [electron 12705](https://github.com/electron/electron/issues/12705)

Hi,

## Use Case
Our web app allows users to change their preferred language. (Accept-Language Header)

Is it possible to change the default BrowserWindow context menu language?

## Currently
![image](https://user-images.githubusercontent.com/5538260/39198416-ea0596fa-47de-11e8-8584-f6375ea17455.png)

In this example the user has chosen 'fr', and we use this language for the spellchecker, but the context menu shows in English.

(My Local machine, Mac OS, English)

**Comment by WilliamHolmes** [comment]
**OR** another option (for my use case) to remove everything except the spelling suggestions.

**Comment by WilliamHolmes** [comment]
*UPDATE*
FYI @Slapbox
I've managed to find where to change these strings.
`ContextMenuBuilder.setAlternateStringFormatter`
eg.
```javascript
  window.spellCheckHandler = new SpellCheckHandler();
  window.spellCheckHandler.attachToInput();
  window.spellCheckHandler.switchLanguage(lang);
  window.contextMenuBuilder = new ContextMenuBuilder(window.spellCheckHandler, null, true);
  window.contextMenuBuilder.setAlternateStringFormatter({
    copyMail: () => `test_copyMail`,
    copyLinkUrl: () => `test_copyLinkUrl`,
    openLinkUrl: () => `test_openLinkUrl`,
    copyImageUrl: () => `test_copyImageUrl`,
    copyImage: () => `test_copyImage`,
    addToDictionary: () => `test_addToDictionary`,
    lookUpDefinition: ({word}) => `test_lookUpDefinition "${word}"`,
    searchGoogle: () => `test_searchGoogle`,
    cut: () => `test_cut`,
    copy: () => `test_copy`,
    paste: () => `test_paste`,
    inspectElement: () => `test_inspectElement`
  });
```
![image](https://user-images.githubusercontent.com/5538260/39266391-d0f7e76a-48c1-11e8-8f35-132a0b571cd2.png)

**Comment by WilliamHolmes** [comment]
Im closing this issue, as this satisfies my requirements.

**Comment by Slapbox** [comment]
Nice work! Thanks for providing an update for everyone's benefit.
