### ISSUE TITLE
Allow "Add to dictionary" feature in Windows

### ISSUE THREAD

**Issue by iamgabrielma** [electron-userland/electron-spellchecker#126]
This seems to be only available for OSX but doesn't work in Windows. This is a screenshot from Simplenote, which uses this module for spell checking:

![image 1](https://user-images.githubusercontent.com/3812076/47363586-56713900-d701-11e8-93e5-25462902a94a.png)

(internal ref: 1507139-zen, don't mind me :) )

**Comment by Slapbox** [comment]
@iamgabrielma - This repo has been unmaintained for a while. It would be best to close this issue yourself so that discussion is more centralized in #36.
