### ISSUE TITLE
Issue packaging for Windows

### ISSUE THREAD

**Issue by eddievagabond** [electron-userland/electron-spellchecker#16]
I am having trouble packaging this module for Windows. I am able to get it working on the Mac build. Have there been any reported issues packaging for windows? Are there any workarounds? The error I receive is 

Uncaught Error %1 is not a valid Win32 application. ...@paulbetts\spellchecker\build\Realse\spellchecker.node

**Comment by paulcbetts** [comment]
Read the electron section on native modules
