### ISSUE TITLE
Exception in main process when right clicking for context menu

### ISSUE THREAD

**Issue by Camyll** [electron-userland/electron-spellchecker#22]
When using the spellchecker in my app on a mac, every time I right click, the app crashes. I've been told that this behavior has happened on Windows before as well but I have not experienced it. 

This is the stack trace associated with the exception being thrown:
![image](https://cloud.githubusercontent.com/assets/8239759/20120003/d6e89e7c-a5bf-11e6-97ed-9d6c08ffe77e.png)

**Comment by akashnimare** [comment]
@camyll how are you using it? It works great for me on all platforms.

**Comment by tomimiot** [comment]
@akashnimare I have this same error, when I first refresh page in electron and next use right click.

**Comment by stanfieldr** [comment]
I have had this error as well. It only happens when I refresh the page like @tomimiot. I'm going to see if I can figure this out, probably just need to unregister the even on the input

**Comment by stanfieldr** [comment]
Figured this out, see extended example in #29

**Comment by akashnimare** [comment]
@stanfieldr could you resolve it?

**Comment by paulcbetts** [comment]
This is fixed in 1.0.0
