### ISSUE TITLE
Example using spell checking in webview

### ISSUE THREAD

**Issue by ddelpero** [electron-userland/electron-spellchecker#26]
Do you have an example of this working with a webview? I see that the code indicates window or webview should work. When I try to attach the menu to a webview, the menu is never displayed. 

Modified script in index.html:
`<script>
  import SpellCheckHandler from '../src/spell-check-handler';
  import ContextMenuListener from '../src/context-menu-listener';
  import ContextMenuBuilder from '../src/context-menu-builder';
  const webview = document.getElementById('webview-test'')

  webview.spellCheckHandler = new SpellCheckHandler();
  webview.spellCheckHandler.attachToInput();
  webview.spellCheckHandler.currentSpellcheckerChanged.subscribe(() => {
    document.getElementById('detectedLang').innerText = `Current language is ${webview.spellCheckHandler.currentSpellcheckerLanguage}`;
  });

  webview.spellCheckHandler.provideHintText('This is probably the language that you want to check in');
  webview.spellCheckHandler.autoUnloadDictionariesOnBlur();

  let contextMenuBuilder = new ContextMenuBuilder(webview.spellCheckHandler,webview);
  let contextMenuListener = new ContextMenuListener(async (info) => {
    await contextMenuBuilder.showPopupMenu(info);
  },webview);
  </script>`

**Comment by akashnimare** [comment]
@ddelpero Do you see any errors any console?

**Comment by ddelpero** [comment]
No, nothing is in the console. ContextMenuBuilder.showPopupMenu never gets called on a right-click. It seems like in ContextMenuListener.constructor that the assignment of the event doesn't do anything when windowOrWebView is a webview. If I change this.sub.add(contextMenuEvent.subscribe(handler)) to windowOrWebView.oncontextmenu = handler, then I get to ContextMenuBuilder.showPopupMenu. 

However that leads to another issue in ContextMenuBuilder.showPopupMenu.Tthe call to menu.popup() only works with no parameters, or at least I couldn't get it to work the parameter remote.getCurrentWindow(). 

Finally, the last issue was once I get the menu to pop up, I'm stumped trying to get the selected word from the webview. I'm also stumped trying to get an editable field in the webview to underline misspelled words.

**Comment by akashnimare** [comment]
@ddelpero I don't know it's working fine for me. You can have a look here - https://github.com/zulip/zulip-electron/blob/master/app/main/spellchecker.js and https://github.com/zulip/zulip-electron/blob/master/app/main/preload.js#L50

**Comment by ddelpero** [comment]
akashnimare, thanks for the example. To clarify, the issue I'm having is getting the context menu and spell checking to work in a <webview>. Everything works fine if it's attached to window.

**Comment by akashnimare** [comment]
@ddelpero could you please provide me a minimal app reproducing above issue so that I can debug it.

**Comment by ddelpero** [comment]
Here's an example of the menu not working in a webview:
https://github.com/ddelpero/electron-spellchecker/tree/master/example_webview

**Comment by paulcbetts** [comment]
Check out the `example` folder for how to do this
