### ISSUE TITLE
Suggestion doesn't replace misspelled word

### ISSUE THREAD

**Issue by MehediH** [electron-userland/electron-spellchecker#30]
Hi,

I have added `electron-spellchecker` into a `<webview>`. The spellchecker works as expected, and  it also shows the suggestions for misspelled words in the context menu  --  but, when I click one of the suggestions, the misspelled word doesn't actually get replaced.

Here's a GIF:

![loading](https://cloud.githubusercontent.com/assets/10274434/21073705/4a5c2c48-bede-11e6-8f4d-90e109997292.gif)

Is there any way of working around this issue? 

Thanks!

**Comment by MehediH** [comment]
Also, @paulcbetts, in case you want the code I used (this is basically the sample code you provided).

It's in the preloaded script for the webview:

```
    const {SpellCheckHandler, ContextMenuListener, ContextMenuBuilder} = require('electron-spellchecker');

    window.spellCheckHandler = new SpellCheckHandler();
    window.spellCheckHandler.attachToInput();

    window.spellCheckHandler.switchLanguage('en-US');
    var contextMenuBuilder = new ContextMenuBuilder(window.spellCheckHandler);

    var contextMenuListener = new ContextMenuListener((info) => {
        contextMenuBuilder.showPopupMenu(info)
    });
```

**Comment by paulcbetts** [comment]
This should be fixed now
