### ISSUE TITLE
Character Accent Menu is not working

### ISSUE THREAD

**Issue by williambout** [electron-userland/electron-spellchecker#40]
The accent menu doesn't seem to work with electron-spellchecker (long pressing a key will repeat the letter instead of displaying the menu)

![accent menu](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/osx_tipyn_alternate_characters.png)

**Comment by paulcbetts** [comment]
This is an Electron bug, spellchecker doesn't control this
