### ISSUE TITLE
Remote loadURL -> rxjs SourceMaps with wrong path get injected

### ISSUE THREAD

**Issue by Sukram21** [electron-userland/electron-spellchecker#48]
I tried electron-spellchecker with an Electron app which displays a remote web page (displayed via (BrowserWindow) `mainWindow.loadURL("<remote_url")`, not via the `<webview>` tag like in the example project). The highlighting of misspelled words & correction works great, but I noticed that a lot of SourceMap errors get thrown:

```
Failed to parse SourceMap: <remote_url>/<local_path>/node_modules/rxjs/operator/mergeMap.js.map
```
(I have omitted the concrete values of `<remote_url>` and `<local_path>`)

At the same time, the terminal outputs the following error (also multiple times):
```
[45386:0301/145400:ERROR:CONSOLE(6954)] "SyntaxError: Unexpected token < in JSON at position 0", source: chrome-devtools://devtools/bundled/inspector.js (6954)
```

Apparently, the remote_url and my local_path get mixed up somehow. This does not happen when displaying the same page via the `<webview>`tag. Any ideas what went wrong here?

**Comment by paulcbetts** [comment]
This happens whenever you use RxJS with an Electron app :-/   electron-forge apps work around this via an electron-compile hack (https://github.com/electron/electron-compile/commit/f70868e3ae4fa93bc08f1a7a8127e8a7fff2d196)

**Comment by Sukram21** [comment]
Thanks for your answer & the hack :-) 

Is there already an open issue in the Chromium repository for that?

**Comment by paulcbetts** [comment]
It's probably better to file it on Electron, I don't think Chromium will deal with it because it's due to the interaction of node modules and Chromium DevTools

**Comment by Sukram21** [comment]
#### Small update:
Related node issue: https://github.com/nodejs/node/issues/8369

After upgrading to node 7.4.0 (& electron 1.6.2), the developer console shows "DevTools failed to parse SourceMap" **warnings**, no errors as it was the case before. It's something 😄 
In the Electron console, the SyntaxErrors still get thrown.

**Comment by toddhalfpenny** [comment]
@muellermarkus Any chance you can share an example of this working with a remote URL? I'm going round in circles and have nothing working at the moment. Ta.

**Comment by muellermarkus** [comment]
Sorry, I've finished my Electron-related project for now :-/
