### ISSUE TITLE
version mismatch error 

### ISSUE THREAD

**Issue by tborychowski** [electron-userland/electron-spellchecker#49]
I cannot make it work.
It installs normally (there are some node-gyp warnings, but overall it is successful), but when I `require` it in the app, I get the following error:

![screen shot 2017-03-02 at 08 58 29](https://cloud.githubusercontent.com/assets/392513/23500119/c330139a-ff26-11e6-9f67-e3e7b3ad3b62.png)

I tried everything (e.g. matching your example's dependencies) but nothing helps.
The odd thing is that the example works!

**Comment by Sukram21** [comment]
Hey, I had the same problem and could make it work:

**Solution:** Install `electron-rebuild` as a devDependency and run `./node_modules/.bin/electron-rebuild` (repeat whenever you install a new npm package). 

**Source:** https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#installing-modules-and-rebuilding-for-electron

Hope this solves your problem, too. 😊

**Comment by tborychowski** [comment]
Thanks @Sukram21,
I'm using `electron-prebuilt`, and that seems too much hassle.
I tried that and got 10 screens of errors in the terminal :-(

**Comment by Sukram21** [comment]
Oh, what a pitty 😕

Here are some notes I have taken before discovering the easier solution I suggested in my last comment:
```bash
# For spell checking to work (see https://github.com/electron-userland/electron-builder/issues/453), 
# as there, we need to compile native depedencies
# <target> is the current Electron version (see `package.json`), 
# <abi> is the ABI (https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/js-ctypes_reference/ABI) this Electron version is expecting. To see which version is expecting which ABI, see https://www.npmjs.com/package/electron-abi
# For more, see this discussion (https://github.com/electron-userland/electron-builder/issues/453) 
# and these links (https://electron.atom.io/docs/tutorial/using-native-node-modules/#modules-that-rely-on-node-pre-gyp 
# and https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)
# Lately, <electron-version> was 1.4.15, <expected-abi> was 50
npm rebuild --runtime=electron --target=<electron-version> --abi=<expected-abi> --disturl=https://atom.io/download/atom-shell
```

Maybe you can get something out of this? For me, both approaches work.

**Comment by paulcbetts** [comment]
> I might try to implement that functionality myself on a lower level, using node-spellcheck or sth.

node-spellcheck is the module that we're using too. If you don't want to deal with native modules, use electron-forge, it will handle all of this sitch for you
