### ISSUE TITLE
spellCheckHandler.switchLanguage doesn't do anything

### ISSUE THREAD

**Issue by miloszfalinski** [electron-userland/electron-spellchecker#50]
I'm adding spellchecker in the webview following the webview example, and currently the language is always being set as 'en-US'. 

The use case here is -  I know what language the user is going to be typing in, so I can set it for them manually, but `spellCheckHandler` seems to be ignoring the string I pass in `window.spellCheckHandler.switchLanguage()`: 

```
window.spellCheckHandler.switchLanguage(formattedLocale); // when eg. formattedLocale = 'pl-PL'
console.log('should set to: ' + formattedLocale); // 'should set to: pl-PL'
console.log('is set to: ' + window.spellCheckHandler.currentSpellcheckerLanguage); //  'is set to: 'en-US'
```

I had a look at the source code, could this be overridden by: https://github.com/electron-userland/electron-spellchecker/blob/master/src/spell-check-handler.js#L149? My system language is not en-US. 

Note that spellcheck works with the en-US locale, including replacing words, etc. I don't see any errors with downloading dictionaries - nothing in the console at all. 

EDIT: My system language is not en-US, but it was en-GB. It seems that changing the primary system language to e.g. `pl-PL` will enable spellcheck in that language. Still, an option to override that on macOS would be nice, as not everyone might have the system language set as the language they would like to write in.

**Comment by paulcbetts** [comment]
What operating system is this? macOS currently ignores all switchLanguage calls and relies on macOS's garbagetown "Automatic Language Detection"

**Comment by miloszfalinski** [comment]
@paulcbetts yes, that's on macOS. I figured it's the native language detection after looking through the code. Is there a plan to change that in the future? 

The native detection works well, but it's not documented anywhere in the package, so it was a bit confusing as to what was going on.
