### ISSUE TITLE
cld.node not found on Windows

### ISSUE THREAD

**Issue by beljand** [electron-userland/electron-spellchecker#51]
Electron ver: 1.6.2
Node: 7.4.0
electron-spellchecker: 1.0.4

Error gets thrown every first time a word gets checked, then input that user was in loses focus - after that spellchecker still works as normal.

`node_modules\@paulcbetts\cld\build\Release\cld.node not found in app.asar`

**Comment by paulcbetts** [comment]
You need to exclude .node files from your ASAR package using asar.unpacked.
