### ISSUE TITLE
Any way to exclude certain areas from spellchecking?

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-spellchecker#53]
I have some code highlighting in my application I'd love to exclude from spellchecking if possible. Is this at all possible?

**Comment by paulcbetts** [comment]
@Slapbox You probably need to use the standard web ways to disable spellchecking (i.e. the same way you'd do it on a website) - electron-spellchecker has no context about which parts of the document are being checked, it only gets the word to check, so it would be very difficult to implement this in electron-spellchecker

**Comment by Slapbox** [comment]
Initially it was not working for me to use the `spellcheck="false"` attribute, but it does indeed work. Thanks for the great package!

**Comment by Slapbox** [comment]
I believe this is still an issue. Maybe I'm just crazy. When you have a `contenteditable` / `spellcheck="false"` element with `spellcheck="true"` elements nested within it, it works fine.

But when the hierarchy is reversed and you place `contenteditable` / `spellcheck="true"` at the top and nest elements with `spellcheck="false"` within it, spellcheck remains turned on for all children.

**Comment by Slapbox** [comment]
So I made a clean Electron project and works fine there... I am totally baffled. 

In my real project, if I type into the `div` with `spellcheck="off"` spellcheck does appear to be off, until I move my focus to any area where `spellcheck="on"` and then return. Upon returning focus to the `spellcheck="off"` `div`, spellcheck suddenly turns on there, even though it remains set to off in the DOM.

**Comment by Slapbox** [comment]
The issue only affects nested `contenteditable` elements as far as I can tell. My project uses React 16.

**Comment by Slapbox** [comment]
Double-layer `spellcheck="false"` does work, as below:

```
<span contentEditable="true" spellCheck="true">
          HERE SPELLCHECK IS ON <br />
          <span contentEditable="true" spellCheck="false">
            HERE SPELLCHECK SHOULD BE OFF, BUT IS NOT <br />
            <span contentEditable="true" spellCheck="false">
              HERE SPELLCHECK SHOULD BE OFF, AND IT IS
            </span>
          </span>
        </span>
```

**Comment by Slapbox** [comment]
I have also tried setting `lang="zxx"` at per [this StackOverflow answer](https://stackoverflow.com/a/22150276/6025788) without luck.

**Comment by Slapbox** [comment]
I seem to have been using version 1.2.0 of this package, which I don't even see in the commit history... I just installed 1.1.2 and so far so good.
