### ISSUE TITLE
Cannot read property 'Menu' of undefined

### ISSUE THREAD

**Issue by liyamahendra** [electron-userland/electron-spellchecker#58]
After I installed the module I get the following error:

> App threw an error during load 
> TypeError: Cannot read property 'Menu' of undefined

I'm working on Mac and the electron version is: 1.4.1

**Comment by ccorcos** [comment]
@liyamahendra I think you have to make sure to `require("electron-spellchecker")` inside the client

**Comment by ccorcos** [comment]
Actually, looking at the example, looks like it needs to go in preload.js

**Comment by akashnimare** [comment]
@ccorcos yes, put it in preload.js.
