### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-spellchecker#62]
https://github.com/electron-userland/electron-spellchecker/blob/master/src/promisify.js#L3

Getting this warning when bundling with webpack

```js
WARNING in ./~/electron-spellchecker/lib/promisify.js
10:31-41 Critical dependency: the request of a dependency is an expression
```

**Comment by paulcbetts** [comment]
Don't use Webpack with electron-spellchecker, just use regular node modules

**Comment by ccorcos** [comment]
This is such an easy fix though:

```js
import pify from 'pify';

module.exports = {
  fs: pify(require("fs"))
  mkdirp: pify(require("mkdirp"))
  rimraf: pify(require("rimraf"))
}
```

Webpack has a target build specifically for electron -- both `electron-main` and `electron-renderer` targets that take care of externalizing all of the relevant dependencies.

https://webpack.js.org/configuration/target/#target

This will minimize your builds (so we have 90MB apps) and give you all of the other features of Webpack.

**Comment by paulcbetts** [comment]
@ccorcos If it's an easy fix that doesn't mess with anyone else then I'd be willing to take a PR for it for sure
