### ISSUE TITLE
On Windows, do still need to rebuild when packing the app?

### ISSUE THREAD

**Issue by djalmaaraujo** [electron-userland/electron-spellchecker#64]
On Windows, do still need to rebuild when packing the app? I was using another module, and we need to rebuild the native modules. With your module, we still need to do this?

Thanks

**Comment by paulcbetts** [comment]
This module uses native modules, yes. You shouldn't need to rebuild again when you package your application though, unless your build process is Doing It Wrong

**Comment by djalmaaraujo** [comment]
@paulcbetts Thanks for the fast response, so just to be clear:

https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

> If your app has native dependencies, it can be compiled only on the target platform. prebuild is a solution, but most node modules don't provide prebuilt binaries. By default build from sources is forced, set npmSkipBuildFromSource to true to use prebuild binaries (if available).

If I am using a CI for windows, I still need to build on the specific platform, right?

**Comment by paulcbetts** [comment]
On CI yeah, since you've _never_ built the module for Electron, you'll have to electron-rebuild. In the _interactive_ case where you're packaging locally, since during development you've probably already built the module for Electron once, you shouldn't have to do it again

**Comment by djalmaaraujo** [comment]
@paulcbetts Thanks for your answer.

**Comment by averissimo** [comment]
@djalmaaraujo are you using a public CI to build it in windows? if so can you share which one is and a project that is doing that :)

it would be awesome, as I'm starting to look into how to do it :)

**Comment by djalmaaraujo** [comment]
@averissimo By the time I was using AppVeyor. Can't share the code because I don't work on the project anymore.
