### ISSUE TITLE
TypeError: Cannot read property 'Menu' of undefined when loading the module via require('electron').remote.require('electron-spellchecker')

### ISSUE THREAD

**Issue by MTRNord** [electron-userland/electron-spellchecker#70]
This line fails when I load it using `require('electron').remote.require('electron-spellchecker')` in render.
https://github.com/electron-userland/electron-spellchecker/blob/91e7be8e8957440f5dd039098364965e59605691/src/context-menu-builder.js#L4

**Comment by MTRNord** [comment]
PS I use reactjs with webpack

**Comment by MTRNord** [comment]
Fixed via adding and resolve alias

**Comment by sachinrekhi** [comment]
@MTRNord I'm running into this same error. Would you mind providing more details on how you resolved it? Wasn't sure exactly what "fixed via adding and resolve alias" meant. Thanks!

**Comment by paulcbetts** [comment]
A much better alternative to using Webpack with Electron apps is to use electron-forge, which handles all of the things that Webpack does with zero configuration, and bonus, also doesn't have weirdo bugs like this :)

**Comment by MTRNord** [comment]
@paulcbetts sadly in my case I wasn't able to use it as the project is mainly aimed for web and the run only one webpack config for both electron and web :/

**Comment by eteisman** [comment]
My application uses SystemJS. It is not an option to rewrite it to WebPack, just for one library.

When I read "please use reactjs plus webpack", I am not happy.  That is not a solution.

**Comment by eteisman** [comment]
OK, I have figured it out.

This article had the solution for me.
  https://ourcodeworld.com/articles/read/485/how-to-implement-and-enable-the-grammar-and-spellchecker-in-electron-framework


I did not use SystemJs or Webpack. 
Instead I just loaded that code immeditely in de 'index.html' file that is load by my electron script on startup.


Some of the code need to be loaded in the document.onLoad event.
Also to run it properly I had to rebuild my node libraries, as described in the article above.

Two usefull node tools for rebuilding native node libraries are:
electron-rebuild and windows-build-tools. The "electron-rebuild" can rebuild native libraries.
For that you need Python and/or MSBuild. These can be installed with "windows-build-tools"


So 'npm install windows-build-tools --save-dev', plus 'npm install electron-rebuild --save-dev'
Then run ./node_modules/.bin/electron-rebuild to rebuild the libraries
