### ISSUE TITLE
Automatic language detection on macOS can't work that way

### ISSUE THREAD

**Issue by awein** [electron-userland/electron-spellchecker#81]
The broken spell checking in electron apps is bothering me for a while and I decided to look into the root cause.
It might be obvious for you but as it turns out: Spell checking is done "word by word"!

The macOS implementation is using the built in frameworks like it should but it's kind of no surprise that language detection based on a single word has to fail quite a lot. Especially in case the misspelled word is correct in a different language.

**Comment by paulcbetts** [comment]
> It might be obvious for you but as it turns out: Spell checking is done "word by word"!

This is how Chromium's spell check works.
